# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-27 18:07
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SalePost',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('make', models.CharField(max_length=20)),
                ('model', models.CharField(max_length=20)),
                ('type', models.CharField(max_length=20)),
                ('size', models.CharField(max_length=20)),
                ('age', models.IntegerField()),
                ('original_price', models.IntegerField()),
                ('quoted_price', models.IntegerField()),
                ('city', models.CharField(max_length=20)),
                ('state', models.CharField(max_length=20)),
                ('shipping', models.CharField(max_length=20)),
                ('bill', models.CharField(max_length=20)),
                ('negotiable', models.CharField(max_length=20)),
                ('other_details', models.CharField(max_length=20)),
                ('published_date', models.DateTimeField(blank=True, null=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
